### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by SikaStar** [Ontheway361/dul-pytorch#10]
Hi, could you share me the training and tesing dataset?

**Comment by Ontheway361** [comment]
@SikaStar 
training dataset : casia_webface or ms1m_clean;
test dataset : lfw, agedb-30, et.al 
Note : the faces in both training/test data are aligned and scaled to 112 x 112.
those dataset/benchmark can be easily download at [DataZoo](https://github.com/deepinsight/insightface/wiki/Dataset-Zoo#megaface), which provided by insightface.
