### ISSUE TITLE
about self.gamma * logvar + self.beta in dul_reg.py

### ISSUE THREAD

**Issue by canteen-man** [Ontheway361/dul-pytorch#12]
I don't find the gamma and beta at the step in the paper.Why add the gamma and beta here.

**Comment by canteen-man** [comment]
``

**Comment by XinWangg** [comment]
Did you solved the problem??

**Comment by canteen-man** [comment]
@XinWangg ，Yes
用这篇论文里的回归方法训练，如果加载预训练模型，分子（label-mu）^2会很快稳定在一个小数上，比如0.0005这种的，然后假设固定这个分子，可以把这个loss function画出函数曲线。代码里的gamma和beta就是直接定位到曲线里的最低点。x轴的最低点的就在-7点左右。
