### ISSUE TITLE
Any result reported?

### ISSUE THREAD

**Issue by zehuichen123** [Ontheway361/dul-pytorch#2]
Nice project! Any results reported based on your code? Thanks!

**Comment by Ontheway361** [comment]
I‘m sorry there is  no any experimental result, but I will release the result as soon as I finished the experiment.

**Comment by Ontheway361** [comment]
> Nice project! Any results reported based on your code? Thanks!
I‘m sorry there is no any experimental result, but I will release the result as soon as I finished the experiment.

**Comment by Ontheway361** [comment]
@zehuichen123 
I‘m sorry there is no any experimental result, but I will release the result as soon as I finished the experiment.

**Comment by zehuichen123** [comment]
I see, Thanks!
